name: Sync to Hugging Face
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure Git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Force push to Hugging Face Space (Replace username and space-name with your HF username and Space name if they are different)
          # We use force push to make sure Hugging Face matches GitHub exactly
          git push --force https://abdelrahmanyassin1918:$HF_TOKEN@huggingface.co/spaces/abdelrahmanyassin1918/Elshorbagy-Store main
